name: Data Refresh Dev

on: 
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  data_refresh_dev:
    name: covid19Italy dataset refresh
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/covid19italy:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'dev'
      - name: Refresh the data
        run: bash ./data_raw/data_refresh.bs "dev"
